name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify dist present
        run: |
          test -f packages/core/dist/esm/math/mat4.js
          test -f packages/renderers/dist/esm/webgl2/lines.js
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
